Repository openhtmltopdf/openhtmltopdf, pull requests merged in 2024-02, with the labels that each got.

#7 Updates to the GitHub Actions workflow
  .github/workflows/maven.yml
Labels: enhancement

#8 Improve ClassCondition performance
  openhtmltopdf-core/src/main/java/com/openhtmltopdf/css/newmatch/Condition.java
Labels: performance

#11 PDFBox version 3 documentation update
  openhtmltopdf-objects/pom.xml
  openhtmltopdf-pdfbox/pom.xml
Labels: documentation
